<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.jenkins-ci.plugins</groupId>
		<artifactId>plugin</artifactId>
		<version>6.2211.v27f680c93c53</version>
		<relativePath />
	</parent>

	<artifactId>keycloak</artifactId>
	<version>${revision}${changelist}</version>
	<name>Keycloak Authentication Plugin</name>
	<description>Integrates with Keycloak Authentication</description>
	<packaging>hpi</packaging>

	<url>https://github.com/jenkinsci/keycloak-plugin</url>

	<issueManagement>
		<system>jira</system>
		<url>https://issues.jenkins-ci.org/</url>
	</issueManagement>

	<properties>
		<revision>2.4.0</revision>
		<changelist>-SNAPSHOT</changelist>
		<gitHubRepo>jenkinsci/keycloak-plugin</gitHubRepo>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<keycloak.version>25.0.3</keycloak.version>
		<!-- authz client on own release schedule -->
		<keycloak.authz.client.version>26.0.7</keycloak.authz.client.version>
		<!-- https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ -->
		<jenkins.baseline>2.504</jenkins.baseline>
		<jenkins.version>2.539</jenkins.version>
		<hpi.compatibleSinceVersion>2.3.1</hpi.compatibleSinceVersion>
		<ban-commons-lang-2.skip>false</ban-commons-lang-2.skip>
	</properties>

	<licenses>
		<license>
			<name>MIT license</name>
			<comments>All source code is under the MIT license.</comments>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>devlauer</id>
			<name>Lauer</name>
			<email>dev.lauer@elnarion.de</email>
			<timezone>+1:00</timezone>
		</developer>
		<developer>
			<id>mnadeem</id>
			<name>Mohammad Nadeem</name>
			<email>coolmind182006@gmail.com</email>
			<timezone>+5:30</timezone>
		</developer>
		<developer>
			<name>Thorsten (askannon)</name>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:https://github.com/${gitHubRepo}.git</connection>
		<developerConnection>scm:git:https://github.com/${gitHubRepo}.git</developerConnection>
		<url>https://github.com/${gitHubRepo}</url>
		<tag>${scmTag}</tag>
	</scm>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.jenkins.tools.bom</groupId>
				<artifactId>bom-${jenkins.baseline}.x</artifactId>
				<version>5681.v79d2ddf61465</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-core</artifactId>
			<version>${keycloak.version}</version>
			<!-- provided by jackson2-api-->
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-databind</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.datatype</groupId>
					<artifactId>jackson-datatype-jsr310</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.datatype</groupId>
					<artifactId>jackson-datatype-jdk8</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.activation</groupId>
					<artifactId>jakarta.activation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-authz-client</artifactId>
			<version>${keycloak.authz.client.version}</version>
			<!-- provided by jackson2-api-->
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-databind</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.datatype</groupId>
					<artifactId>jackson-datatype-jsr310</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.datatype</groupId>
					<artifactId>jackson-datatype-jdk8</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-adapter-core</artifactId>
			<version>${keycloak.version}</version>
			<!-- provided by bouncycastle-api-->
			<exclusions>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcpkix-jdk18on</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcutil-jdk18on</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcprov-jdk18on</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-adapter-spi</artifactId>
			<version>${keycloak.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jenkins-ci.plugins</groupId>
			<artifactId>mailer</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jdk14</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jenkins-ci.plugins</groupId>
			<artifactId>jackson2-api</artifactId>
		</dependency>
    <dependency>
			<groupId>org.jenkins-ci.plugins</groupId>
			<artifactId>bouncycastle-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.kohsuke</groupId>
			<artifactId>access-modifier-suppressions</artifactId>
			<version>${access-modifier-checker.version}</version>
			<scope>provided</scope>
    </dependency>
		<dependency>
			<groupId>io.jenkins</groupId>
			<artifactId>configuration-as-code</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.jenkins.configuration-as-code</groupId>
			<artifactId>test-harness</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.jenkins.plugins</groupId>
			<artifactId>javax-activation-api</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
    </pluginRepositories>
</project>
